export const projectData = [
  {
    title: 'Poetiquette',
    description: "A place for people to share poetry and short stories with each other. Like Twitter for poetry",
    //  image: '/images/1.png',
      tags: ['React', 'Next', 'Firebase'],
    url: 'https://google.com',
    code: 'https://google.com',
    id: 0,
  },
  {
    title: 'Showbiz Quiz',
    description:"An educational mobile app with quizzes that helps artists with understanding the music industry",
    // image: '/images/2.png',
    tags: ['Flutter', 'Firebase'],
    url: 'https://google.com',
    code: 'https://google.com',
    id: 1,
  },
  {
    title: 'Bug Tracker',
    description: "A useful tool to keep track of which bugs to fix and their status of repair",
      //image: '/images/3.jpg',
      tags: ['C#', '.NET', 'Blazor'],
    url: 'https://google.com',
    code: 'https://google.com',
    id: 2,
  },
  {
    title: 'Libaria',
    description: "A Library Managment Application",
    // image: '/images/4.jpg',
    tags: ['Go', 'MySQL', 'React'],
    url: 'https://google.com',
    code: 'https://google.com',
    id: 3,
  },
  {
    title: 'Contracto',
    description: "A Contract Revision Version Control Application",
    // image: '/images/4.jpg',
    tags: ['C#', 'SQL Server', 'Blazor'],
    url: 'https://google.com',
    code: 'https://google.com',
    id: 4,
  },
  {
    title: 'CryptoLand',
    description: "A Cryptocurrency Tracker and Knowledge Hub",
    // image: '/images/4.jpg',
    tags: ['React', 'Redux', 'Firebase'],
    url: 'https://google.com',
    code: 'https://google.com',
    id: 5,
  },
];

